# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/imagemapplugingui.ui'
#
# Created: Fri Oct  1 23:31:50 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ImageMapPluginGui(object):
    def setupUi(self, ImageMapPluginGui):
        ImageMapPluginGui.setObjectName("ImageMapPluginGui")
        ImageMapPluginGui.resize(718, 513)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ImageMapPluginGui.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(ImageMapPluginGui)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(ImageMapPluginGui)
        self.label.setPixmap(QtGui.QPixmap(":/imagemap.png"))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 3, 1)
        self.line1 = QtGui.QFrame(ImageMapPluginGui)
        self.line1.setMaximumSize(QtCore.QSize(2, 32767))
        self.line1.setFrameShape(QtGui.QFrame.VLine)
        self.line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1.setFrameShape(QtGui.QFrame.VLine)
        self.line1.setFrameShadow(QtGui.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.gridLayout.addWidget(self.line1, 0, 1, 3, 1)
        self.txtHeading = QtGui.QLabel(ImageMapPluginGui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtHeading.sizePolicy().hasHeightForWidth())
        self.txtHeading.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(24)
        font.setWeight(50)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setBold(False)
        self.txtHeading.setFont(font)
        self.txtHeading.setAlignment(QtCore.Qt.AlignCenter)
        self.txtHeading.setObjectName("txtHeading")
        self.gridLayout.addWidget(self.txtHeading, 0, 2, 1, 1)
        self.textEdit = QtGui.QTextEdit(ImageMapPluginGui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 2, 1, 1)
        self.progressBar = QtGui.QProgressBar(ImageMapPluginGui)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 3, 0, 1, 3)
        self.buttonBox = QtGui.QDialogButtonBox(ImageMapPluginGui)
        self.buttonBox.setEnabled(True)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 0, 1, 3)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblSetImageSize = QtGui.QLabel(ImageMapPluginGui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSetImageSize.sizePolicy().hasHeightForWidth())
        self.lblSetImageSize.setSizePolicy(sizePolicy)
        self.lblSetImageSize.setObjectName("lblSetImageSize")
        self.gridLayout_3.addWidget(self.lblSetImageSize, 1, 0, 1, 1)
        self.lblFilename = QtGui.QLabel(ImageMapPluginGui)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFilename.sizePolicy().hasHeightForWidth())
        self.lblFilename.setSizePolicy(sizePolicy)
        self.lblFilename.setObjectName("lblFilename")
        self.gridLayout_3.addWidget(self.lblFilename, 3, 0, 1, 1)
        self.btnBrowse = QtGui.QPushButton(ImageMapPluginGui)
        self.btnBrowse.setObjectName("btnBrowse")
        self.gridLayout_3.addWidget(self.btnBrowse, 3, 3, 1, 1)
        self.chkBoxHref = QtGui.QCheckBox(ImageMapPluginGui)
        self.chkBoxHref.setChecked(True)
        self.chkBoxHref.setObjectName("chkBoxHref")
        self.gridLayout_3.addWidget(self.chkBoxHref, 4, 0, 1, 1)
        self.cmbAttributesHref = QtGui.QComboBox(ImageMapPluginGui)
        self.cmbAttributesHref.setAcceptDrops(True)
        self.cmbAttributesHref.setEditable(False)
        self.cmbAttributesHref.setObjectName("cmbAttributesHref")
        self.gridLayout_3.addWidget(self.cmbAttributesHref, 4, 1, 1, 3)
        self.chkBoxOnClick = QtGui.QCheckBox(ImageMapPluginGui)
        self.chkBoxOnClick.setObjectName("chkBoxOnClick")
        self.gridLayout_3.addWidget(self.chkBoxOnClick, 5, 0, 1, 1)
        self.cmbAttributesOnClick = QtGui.QComboBox(ImageMapPluginGui)
        self.cmbAttributesOnClick.setEnabled(False)
        self.cmbAttributesOnClick.setObjectName("cmbAttributesOnClick")
        self.gridLayout_3.addWidget(self.cmbAttributesOnClick, 5, 1, 1, 3)
        self.chkBoxOnMouseOver = QtGui.QCheckBox(ImageMapPluginGui)
        self.chkBoxOnMouseOver.setObjectName("chkBoxOnMouseOver")
        self.gridLayout_3.addWidget(self.chkBoxOnMouseOver, 6, 0, 1, 1)
        self.cmbAttributesOnMouseOver = QtGui.QComboBox(ImageMapPluginGui)
        self.cmbAttributesOnMouseOver.setEnabled(False)
        self.cmbAttributesOnMouseOver.setObjectName("cmbAttributesOnMouseOver")
        self.gridLayout_3.addWidget(self.cmbAttributesOnMouseOver, 6, 1, 1, 3)
        self.chkBoxOnMouseOut = QtGui.QCheckBox(ImageMapPluginGui)
        self.chkBoxOnMouseOut.setObjectName("chkBoxOnMouseOut")
        self.gridLayout_3.addWidget(self.chkBoxOnMouseOut, 7, 0, 1, 1)
        self.cmbAttributesOnMouseOut = QtGui.QComboBox(ImageMapPluginGui)
        self.cmbAttributesOnMouseOut.setEnabled(False)
        self.cmbAttributesOnMouseOut.setObjectName("cmbAttributesOnMouseOut")
        self.gridLayout_3.addWidget(self.cmbAttributesOnMouseOut, 7, 1, 1, 3)
        self.txtFileName = QtGui.QLineEdit(ImageMapPluginGui)
        self.txtFileName.setObjectName("txtFileName")
        self.gridLayout_3.addWidget(self.txtFileName, 3, 1, 1, 2)
        self.spinBoxImageWidth = QtGui.QSpinBox(ImageMapPluginGui)
        self.spinBoxImageWidth.setMinimum(150)
        self.spinBoxImageWidth.setMaximum(15000)
        self.spinBoxImageWidth.setProperty("value", 400)
        self.spinBoxImageWidth.setObjectName("spinBoxImageWidth")
        self.gridLayout_3.addWidget(self.spinBoxImageWidth, 1, 1, 1, 1)
        self.chkBoxSelectedOnly = QtGui.QCheckBox(ImageMapPluginGui)
        self.chkBoxSelectedOnly.setObjectName("chkBoxSelectedOnly")
        self.gridLayout_3.addWidget(self.chkBoxSelectedOnly, 9, 0, 1, 4)
        self.btnSetImageSize = QtGui.QPushButton(ImageMapPluginGui)
        self.btnSetImageSize.setObjectName("btnSetImageSize")
        self.gridLayout_3.addWidget(self.btnSetImageSize, 1, 3, 1, 1)
        self.spinBoxImageHeight = QtGui.QSpinBox(ImageMapPluginGui)
        self.spinBoxImageHeight.setMinimum(150)
        self.spinBoxImageHeight.setMaximum(15000)
        self.spinBoxImageHeight.setProperty("value", 400)
        self.spinBoxImageHeight.setObjectName("spinBoxImageHeight")
        self.gridLayout_3.addWidget(self.spinBoxImageHeight, 1, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 2, 2, 1, 1)

        self.retranslateUi(ImageMapPluginGui)
        QtCore.QMetaObject.connectSlotsByName(ImageMapPluginGui)

    def retranslateUi(self, ImageMapPluginGui):
        ImageMapPluginGui.setWindowTitle(QtGui.QApplication.translate("ImageMapPluginGui", "Html Image Map Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.txtHeading.setText(QtGui.QApplication.translate("ImageMapPluginGui", "Html Image Map Plugin", None, QtGui.QApplication.UnicodeUTF8))
        self.textEdit.setHtml(QtGui.QApplication.translate("ImageMapPluginGui", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\">This plugin will generate a html-file and corresponding image file. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:6pt;\"> </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\">- User can set image size (mapcanvas will be resized)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\">- Can be used for active (multi)polygon or point vector layer (e.g. shapefiles or postgis-layers).</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\">- The html-file will contain the &lt;img&gt; and image &lt;map&gt; source .</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\';\">- Use \'Selected features only\' to generate &lt;area&gt; tags for selected features only.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.lblSetImageSize.setText(QtGui.QApplication.translate("ImageMapPluginGui", "Set Map/Image size", None, QtGui.QApplication.UnicodeUTF8))
        self.lblFilename.setText(QtGui.QApplication.translate("ImageMapPluginGui", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setText(QtGui.QApplication.translate("ImageMapPluginGui", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBoxHref.setText(QtGui.QApplication.translate("ImageMapPluginGui", "href attr", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbAttributesHref.setToolTip(QtGui.QApplication.translate("ImageMapPluginGui", "field to be used in HREF tag", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBoxOnClick.setText(QtGui.QApplication.translate("ImageMapPluginGui", "onClick attr", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBoxOnMouseOver.setText(QtGui.QApplication.translate("ImageMapPluginGui", "onMouseOver attr", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBoxOnMouseOut.setText(QtGui.QApplication.translate("ImageMapPluginGui", "onMouseOut attr", None, QtGui.QApplication.UnicodeUTF8))
        self.txtFileName.setText(QtGui.QApplication.translate("ImageMapPluginGui", "Path and name without extension", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxImageWidth.setSuffix(QtGui.QApplication.translate("ImageMapPluginGui", " px", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxImageWidth.setPrefix(QtGui.QApplication.translate("ImageMapPluginGui", "Width ", None, QtGui.QApplication.UnicodeUTF8))
        self.chkBoxSelectedOnly.setText(QtGui.QApplication.translate("ImageMapPluginGui", "Selected features only", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSetImageSize.setText(QtGui.QApplication.translate("ImageMapPluginGui", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxImageHeight.setSuffix(QtGui.QApplication.translate("ImageMapPluginGui", " px", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxImageHeight.setPrefix(QtGui.QApplication.translate("ImageMapPluginGui", "Height ", None, QtGui.QApplication.UnicodeUTF8))

import imagemapplugin_rc
